### ISSUE TITLE
receive.ino and send.ino have different structure lengths

### ISSUE THREAD

**Issue by RudyFiero** [fmilburn3/ESP-NOW#2]
MSG_LEN 40 for receive.ino
MSG_LEN 15 for send.ino

The structures are not the same size.  (send.ino and receive.ino in the root)

The printed result had me confused for a while. I looked at the code and saw it right away. 

Thank you for these two files. They were a lot clearer for me compared to the other examples I found. (I'm not a programmer so simpler is better) And I appreciate the comments.

I have a little project to do and I will be using your code as a starting point.

**Comment by fmilburn3** [comment]
Thanks!  Changed send so that is 40 also.
