### ISSUE TITLE
can't receive the messages in the receiver

### ISSUE THREAD

**Issue by Ricardosgeral** [fmilburn3/ESP-NOW#3]
Hi Frank

I can't receive any message in the receiver side. Actually i don't even know if i'm actually sending.

Isn't suppose to print something in the serial monitor?
only receive this in the wemos with receive.ino

```
Starting ESP_Now Receiver
Receiver MAC: 84:0D:8E:AD:9D:0F
```

in the send.ino i get

```
Starting ESP-NOW Sender
Sender MAC:   BC:DD:C2:9E:04:C9
Receiver MAC: 84:D:8E:AD:9D:F, channel: 1

Hello World: 0
Hello World: 1
Hello World: 2
Hello World: 3
Hello World: 4
Hello World: 5
Hello World: 6
```

Don't understand what's wrong.
I notice that some of leading zeros are missing in the receiver MAC shown in serial print by the send.ino but i guess that that is just a question with the print function.

**Comment by fmilburn3** [comment]
Hi Ricardo,

It should print if it receives something although I admit to just hacking this together quickly and not testing recently - but another user seems to have it working.  Are you using ESP8266 or ESP32?  Also, try the Andreas Spiess code I think I linked to in the description.

**Comment by fmilburn3** [comment]
This is from Andreas Spiess:  https://m.youtube.com/watch?v=6NsBN42B80Q.  Llet me know if you find an error in what I posted.  There seem to be many more posts on this subject since I wrote this.

**Comment by Ricardosgeral** [comment]
Hi Frank

I managed to put it to work but

I've changed the WiFi.mode of the receiver also to station WIFI_STA
`WiFi.mode(WIFI_STA);`                                                     
not sure if i have to do also 
`WiFi.disconnect();`

i'm also using wemos D1 mini in latest Arduino IDE.
